[build]
target-dir = "/tmp/control-frontend"

[target.aarch64-apple-darwin]
rustflags = [
  "-C", "link-arg=-L/opt/homebrew/Cellar/sdl2/2.28.5/lib",
]

[target.x86_64-apple-darwin]
rustflags = [
  "-C", "link-arg=-L/usr/local/Cellar/sdl2/2.30.0/lib",
]

[target.x86_64-pc-windows-msvc]
rustflags = [
   "-C", "link-arg=-LIBPATH:C:/Users/deets/Downloads/SDL2-devel-2.30.1-VC/SDL2-2.30.1/lib/x64"
]


[target.aarch64-unknown-linux-gnu]
linker = "/opt/nova-view-sdk/sysroots/x86_64-pokysdk-linux/usr/bin/aarch64-poky-linux/aarch64-poky-linux-gcc"
rustflags = [
  "-C", "link-arg=--sysroot=/opt/nova-view-sdk/sysroots/cortexa72-poky-linux",
]
