[build]
target-dir = "/tmp/control-frontend"

[target.aarch64-apple-darwin]
rustflags = [
  "-C", "link-arg=-L/opt/homebrew/Cellar/sdl2/2.28.5/lib",
]

[target.x86_64-apple-darwin]
rustflags = [
  "-C", "link-arg=-L/usr/local/Cellar/sdl2/2.30.0/lib",
]


