#![feature(assert_matches, slice_pattern, exclusive_range_pattern)]
pub mod consort;
pub mod ebyte;
pub mod ignition_statemachine;
pub mod input;
pub mod layout;
pub mod render;
pub mod rqparser;
pub mod rqprotocol;
pub mod state;
pub mod timestep;
pub mod visualisation;
